/**
 * stages.js — 술창고 청소 스테이지 데이터
 * (sweep/stage_editor.html 에서 생성)
 *
 * 좌표는 셀 좌표(cx 0~10, cy 0~5) — 이동 격자 한 칸 단위.
 * 장애물 스탬프: 3×3 타일(row-major 9칸) 묶음. null은 투명. block=false는 통행 가능.
 *
 * minSteps/hamiltonian: `node calc_minsteps.js`가 완전 탐색으로 계산한 확정값 —
 * 방 배치(장애물·스폰)를 고치면 반드시 다시 돌려서 갱신할 것. hamiltonian=false면
 * 모든 칸을 한 번씩만 밟는 경로가 없어 최소 1칸은 되밟아야 완주 가능하다는 뜻.
 */

window.SWEEP_OBSTACLES = {
    "포대1": {
        tiles: [
            [18, 5], [19, 5], [20, 5],
            [21, 5], [22, 5], [23, 5],
            [24, 5], [25, 5], [26, 5]
        ]
    },
    "포대2": {
        tiles: [
            [27, 5], [28, 5], [29, 5],
            [30, 5], [31, 5], [32, 5],
            [33, 5], [34, 5], [35, 5]
        ]
    },
    "술박스": {
        tiles: [
            [5, 3], [6, 3], [7, 3],
            [15, 3], [16, 3], [17, 3],
            [22, 3], [23, 3], [24, 3]
        ]
    },
    "작은박스더미": {
        tiles: [
            [8, 3], [8, 3], [8, 3],
            [18, 3], [18, 3], [18, 3],
            [25, 3], [25, 3], [25, 3]
        ]
    },
    "세운술통": {
        tiles: [
            [33, 1], [34, 1], [35, 1],
            [12, 2], [13, 2], [14, 2],
            [30, 2], [31, 2], [32, 2]
        ]
    },
    "누운술통": {
        tiles: [
            [36, 1], [37, 1], [38, 1],
            [15, 2], [16, 2], [17, 2],
            [33, 2], [34, 2], [35, 2]
        ]
    }
};

window.SWEEP_STAGES = [
    { id: "o_1", spawn: { cx: 5, cy: 5 }, minSteps: 51, hamiltonian: false, obstacles: [
            { cx: 2, cy: 1, stamp: "포대1" },
            { cx: 9, cy: 1, stamp: "포대1" },
            { cx: 3, cy: 1, stamp: "포대2" },
            { cx: 5, cy: 1, stamp: "포대2" },
            { cx: 6, cy: 1, stamp: "세운술통" },
            { cx: 7, cy: 1, stamp: "세운술통" },
            { cx: 8, cy: 1, stamp: "세운술통" },
            { cx: 9, cy: 2, stamp: "세운술통" },
            { cx: 8, cy: 4, stamp: "세운술통" },
            { cx: 5, cy: 2, stamp: "세운술통" },
            { cx: 5, cy: 4, stamp: "세운술통" },
            { cx: 4, cy: 4, stamp: "세운술통" },
            { cx: 3, cy: 4, stamp: "세운술통" },
            { cx: 2, cy: 4, stamp: "세운술통" },
            { cx: 2, cy: 3, stamp: "세운술통" }
        ] },
    { id: "o_2", spawn: { cx: 5, cy: 5 }, minSteps: 54, hamiltonian: true, obstacles: [
            { cx: 5, cy: 0, stamp: "세운술통" },
            { cx: 1, cy: 2, stamp: "세운술통" },
            { cx: 1, cy: 3, stamp: "세운술통" },
            { cx: 7, cy: 5, stamp: "포대1" },
            { cx: 7, cy: 4, stamp: "세운술통" },
            { cx: 7, cy: 3, stamp: "세운술통" },
            { cx: 10, cy: 1, stamp: "세운술통" },
            { cx: 10, cy: 0, stamp: "술박스" },
            { cx: 8, cy: 1, stamp: "포대1" },
            { cx: 3, cy: 1, stamp: "포대1" },
            { cx: 3, cy: 4, stamp: "술박스" }
        ] },
    { id: "o_3", spawn: { cx: 5, cy: 5 }, minSteps: 50, hamiltonian: false, obstacles: [
            { cx: 2, cy: 0, stamp: "술박스" },
            { cx: 1, cy: 2, stamp: "세운술통" },
            { cx: 1, cy: 3, stamp: "세운술통" },
            { cx: 2, cy: 3, stamp: "세운술통" },
            { cx: 3, cy: 3, stamp: "세운술통" },
            { cx: 0, cy: 5, stamp: "세운술통" },
            { cx: 8, cy: 4, stamp: "세운술통" },
            { cx: 9, cy: 4, stamp: "세운술통" },
            { cx: 9, cy: 3, stamp: "세운술통" },
            { cx: 9, cy: 2, stamp: "세운술통" },
            { cx: 9, cy: 1, stamp: "세운술통" },
            { cx: 8, cy: 1, stamp: "세운술통" },
            { cx: 4, cy: 1, stamp: "포대1" },
            { cx: 5, cy: 1, stamp: "포대1" },
            { cx: 6, cy: 1, stamp: "포대2" },
            { cx: 5, cy: 3, stamp: "포대1" }
        ] },
    { id: "o_4", spawn: { cx: 5, cy: 5 }, minSteps: 47, hamiltonian: true, obstacles: [
            { cx: 0, cy: 0, stamp: "작은박스더미" },
            { cx: 1, cy: 2, stamp: "세운술통" },
            { cx: 1, cy: 3, stamp: "세운술통" },
            { cx: 2, cy: 3, stamp: "세운술통" },
            { cx: 2, cy: 2, stamp: "세운술통" },
            { cx: 3, cy: 2, stamp: "세운술통" },
            { cx: 4, cy: 2, stamp: "세운술통" },
            { cx: 4, cy: 3, stamp: "세운술통" },
            { cx: 3, cy: 3, stamp: "세운술통" },
            { cx: 6, cy: 2, stamp: "세운술통" },
            { cx: 7, cy: 2, stamp: "세운술통" },
            { cx: 8, cy: 2, stamp: "세운술통" },
            { cx: 9, cy: 2, stamp: "세운술통" },
            { cx: 9, cy: 3, stamp: "세운술통" },
            { cx: 8, cy: 3, stamp: "세운술통" },
            { cx: 7, cy: 3, stamp: "세운술통" },
            { cx: 6, cy: 3, stamp: "세운술통" },
            { cx: 10, cy: 5, stamp: "술박스" }
        ] },
    { id: "o_5", spawn: { cx: 5, cy: 5 }, minSteps: 37, hamiltonian: true, obstacles: [
            { cx: 10, cy: 0, stamp: "술박스" },
            { cx: 0, cy: 0, stamp: "작은박스더미" },
            { cx: 1, cy: 0, stamp: "세운술통" },
            { cx: 9, cy: 0, stamp: "세운술통" },
            { cx: 0, cy: 1, stamp: "세운술통" },
            { cx: 0, cy: 2, stamp: "세운술통" },
            { cx: 0, cy: 3, stamp: "세운술통" },
            { cx: 0, cy: 4, stamp: "세운술통" },
            { cx: 0, cy: 5, stamp: "세운술통" },
            { cx: 1, cy: 5, stamp: "세운술통" },
            { cx: 9, cy: 5, stamp: "세운술통" },
            { cx: 10, cy: 5, stamp: "세운술통" },
            { cx: 10, cy: 4, stamp: "세운술통" },
            { cx: 10, cy: 3, stamp: "세운술통" },
            { cx: 10, cy: 2, stamp: "세운술통" },
            { cx: 10, cy: 1, stamp: "세운술통" },
            { cx: 5, cy: 4, stamp: "세운술통" },
            { cx: 5, cy: 3, stamp: "세운술통" },
            { cx: 5, cy: 2, stamp: "세운술통" },
            { cx: 5, cy: 1, stamp: "세운술통" },
            { cx: 4, cy: 2, stamp: "세운술통" },
            { cx: 4, cy: 3, stamp: "세운술통" },
            { cx: 3, cy: 2, stamp: "세운술통" },
            { cx: 3, cy: 3, stamp: "세운술통" },
            { cx: 6, cy: 2, stamp: "세운술통" },
            { cx: 6, cy: 3, stamp: "세운술통" },
            { cx: 7, cy: 3, stamp: "세운술통" },
            { cx: 7, cy: 2, stamp: "세운술통" }
        ] },
    { id: "o_6", spawn: { cx: 5, cy: 5 }, minSteps: 55, hamiltonian: true, obstacles: [
            { cx: 3, cy: 1, stamp: "세운술통" },
            { cx: 4, cy: 1, stamp: "세운술통" },
            { cx: 9, cy: 1, stamp: "세운술통" },
            { cx: 9, cy: 2, stamp: "세운술통" },
            { cx: 1, cy: 4, stamp: "세운술통" },
            { cx: 2, cy: 4, stamp: "세운술통" },
            { cx: 3, cy: 4, stamp: "술박스" },
            { cx: 7, cy: 4, stamp: "술박스" },
            { cx: 8, cy: 4, stamp: "세운술통" },
            { cx: 2, cy: 2, stamp: "포대1" }
        ] },
    { id: "o_7", spawn: { cx: 5, cy: 5 }, minSteps: 49, hamiltonian: true, obstacles: [
            { cx: 2, cy: 2, stamp: "세운술통" },
            { cx: 2, cy: 3, stamp: "세운술통" },
            { cx: 3, cy: 3, stamp: "세운술통" },
            { cx: 3, cy: 2, stamp: "세운술통" },
            { cx: 4, cy: 2, stamp: "세운술통" },
            { cx: 4, cy: 3, stamp: "세운술통" },
            { cx: 5, cy: 3, stamp: "세운술통" },
            { cx: 5, cy: 2, stamp: "세운술통" },
            { cx: 6, cy: 2, stamp: "세운술통" },
            { cx: 7, cy: 2, stamp: "세운술통" },
            { cx: 6, cy: 3, stamp: "세운술통" },
            { cx: 7, cy: 3, stamp: "세운술통" },
            { cx: 8, cy: 3, stamp: "세운술통" },
            { cx: 8, cy: 2, stamp: "세운술통" },
            { cx: 10, cy: 0, stamp: "술박스" },
            { cx: 0, cy: 5, stamp: "작은박스더미" }
        ] },
    { id: "o_8", spawn: { cx: 5, cy: 5 }, minSteps: 45, hamiltonian: true, obstacles: [
            { cx: 0, cy: 0, stamp: "포대1" },
            { cx: 0, cy: 1, stamp: "포대1" },
            { cx: 0, cy: 2, stamp: "포대1" },
            { cx: 1, cy: 3, stamp: "포대1" },
            { cx: 2, cy: 3, stamp: "포대1" },
            { cx: 3, cy: 3, stamp: "포대1" },
            { cx: 8, cy: 2, stamp: "포대1" },
            { cx: 10, cy: 2, stamp: "포대1" },
            { cx: 10, cy: 3, stamp: "포대1" },
            { cx: 10, cy: 0, stamp: "포대1" },
            { cx: 9, cy: 0, stamp: "포대2" },
            { cx: 8, cy: 0, stamp: "포대2" },
            { cx: 7, cy: 0, stamp: "포대2" },
            { cx: 7, cy: 2, stamp: "포대2" },
            { cx: 9, cy: 2, stamp: "포대2" },
            { cx: 10, cy: 4, stamp: "포대2" },
            { cx: 10, cy: 5, stamp: "포대2" },
            { cx: 0, cy: 4, stamp: "포대2" },
            { cx: 0, cy: 3, stamp: "포대2" },
            { cx: 0, cy: 5, stamp: "포대2" }
        ] },
    { id: "o_9", spawn: { cx: 5, cy: 5 }, minSteps: 47, hamiltonian: true, obstacles: [
            { cx: 9, cy: 1, stamp: "포대2" },
            { cx: 1, cy: 1, stamp: "포대1" },
            { cx: 2, cy: 1, stamp: "세운술통" },
            { cx: 3, cy: 1, stamp: "세운술통" },
            { cx: 4, cy: 1, stamp: "세운술통" },
            { cx: 5, cy: 1, stamp: "세운술통" },
            { cx: 6, cy: 1, stamp: "세운술통" },
            { cx: 7, cy: 1, stamp: "세운술통" },
            { cx: 8, cy: 1, stamp: "세운술통" },
            { cx: 2, cy: 4, stamp: "세운술통" },
            { cx: 3, cy: 4, stamp: "세운술통" },
            { cx: 4, cy: 4, stamp: "세운술통" },
            { cx: 5, cy: 4, stamp: "세운술통" },
            { cx: 6, cy: 4, stamp: "세운술통" },
            { cx: 7, cy: 4, stamp: "세운술통" },
            { cx: 8, cy: 4, stamp: "세운술통" },
            { cx: 9, cy: 4, stamp: "술박스" },
            { cx: 1, cy: 4, stamp: "술박스" }
        ] },
    { id: "o_10", spawn: { cx: 5, cy: 5 }, minSteps: 51, hamiltonian: true, obstacles: [
            { cx: 6, cy: 0, stamp: "포대1" },
            { cx: 6, cy: 3, stamp: "포대1" },
            { cx: 4, cy: 1, stamp: "세운술통" },
            { cx: 4, cy: 2, stamp: "세운술통" },
            { cx: 3, cy: 3, stamp: "세운술통" },
            { cx: 3, cy: 4, stamp: "세운술통" },
            { cx: 1, cy: 5, stamp: "세운술통" },
            { cx: 1, cy: 2, stamp: "세운술통" },
            { cx: 1, cy: 1, stamp: "세운술통" },
            { cx: 10, cy: 2, stamp: "세운술통" },
            { cx: 10, cy: 3, stamp: "세운술통" },
            { cx: 8, cy: 3, stamp: "세운술통" },
            { cx: 8, cy: 4, stamp: "세운술통" },
            { cx: 0, cy: 5, stamp: "포대1" }
        ] },
    { id: "o_11", spawn: { cx: 5, cy: 5 }, minSteps: 47, hamiltonian: true, obstacles: [
            { cx: 2, cy: 1, stamp: "세운술통" },
            { cx: 1, cy: 1, stamp: "세운술통" },
            { cx: 1, cy: 2, stamp: "세운술통" },
            { cx: 2, cy: 2, stamp: "세운술통" },
            { cx: 2, cy: 3, stamp: "세운술통" },
            { cx: 1, cy: 3, stamp: "세운술통" },
            { cx: 1, cy: 4, stamp: "세운술통" },
            { cx: 2, cy: 4, stamp: "세운술통" },
            { cx: 8, cy: 1, stamp: "세운술통" },
            { cx: 7, cy: 1, stamp: "세운술통" },
            { cx: 7, cy: 2, stamp: "세운술통" },
            { cx: 7, cy: 3, stamp: "세운술통" },
            { cx: 8, cy: 3, stamp: "세운술통" },
            { cx: 8, cy: 2, stamp: "세운술통" },
            { cx: 4, cy: 2, stamp: "작은박스더미" },
            { cx: 5, cy: 3, stamp: "작은박스더미" },
            { cx: 4, cy: 3, stamp: "포대1" },
            { cx: 5, cy: 2, stamp: "술박스" }
        ] },
    { id: "o_12", spawn: { cx: 5, cy: 5 }, minSteps: 41, hamiltonian: true, obstacles: [
            { cx: 8, cy: 2, stamp: "술박스" },
            { cx: 2, cy: 2, stamp: "술박스" },
            { cx: 8, cy: 3, stamp: "작은박스더미" },
            { cx: 2, cy: 3, stamp: "작은박스더미" },
            { cx: 7, cy: 1, stamp: "세운술통" },
            { cx: 8, cy: 1, stamp: "세운술통" },
            { cx: 9, cy: 1, stamp: "세운술통" },
            { cx: 9, cy: 2, stamp: "세운술통" },
            { cx: 9, cy: 3, stamp: "세운술통" },
            { cx: 9, cy: 4, stamp: "세운술통" },
            { cx: 8, cy: 4, stamp: "세운술통" },
            { cx: 7, cy: 4, stamp: "세운술통" },
            { cx: 7, cy: 3, stamp: "세운술통" },
            { cx: 7, cy: 2, stamp: "세운술통" },
            { cx: 2, cy: 1, stamp: "세운술통" },
            { cx: 1, cy: 1, stamp: "세운술통" },
            { cx: 1, cy: 2, stamp: "세운술통" },
            { cx: 1, cy: 3, stamp: "세운술통" },
            { cx: 1, cy: 4, stamp: "세운술통" },
            { cx: 2, cy: 4, stamp: "세운술통" },
            { cx: 3, cy: 4, stamp: "세운술통" },
            { cx: 3, cy: 3, stamp: "세운술통" },
            { cx: 3, cy: 2, stamp: "세운술통" },
            { cx: 3, cy: 1, stamp: "세운술통" }
        ] },
    { id: "o_13", spawn: { cx: 5, cy: 5 }, minSteps: 56, hamiltonian: true, obstacles: [
            { cx: 10, cy: 0, stamp: "술박스" },
            { cx: 8, cy: 1, stamp: "술박스" },
            { cx: 6, cy: 1, stamp: "술박스" },
            { cx: 1, cy: 1, stamp: "술박스" },
            { cx: 3, cy: 3, stamp: "술박스" },
            { cx: 1, cy: 4, stamp: "술박스" },
            { cx: 7, cy: 3, stamp: "술박스" },
            { cx: 9, cy: 4, stamp: "술박스" },
            { cx: 6, cy: 5, stamp: "술박스" }
        ] },
    { id: "o_14", spawn: { cx: 5, cy: 5 }, minSteps: 46, hamiltonian: false, obstacles: [
            { cx: 10, cy: 0, stamp: "작은박스더미" },
            { cx: 10, cy: 5, stamp: "술박스" },
            { cx: 0, cy: 5, stamp: "술박스" },
            { cx: 10, cy: 4, stamp: "세운술통" },
            { cx: 9, cy: 4, stamp: "세운술통" },
            { cx: 9, cy: 5, stamp: "세운술통" },
            { cx: 1, cy: 5, stamp: "세운술통" },
            { cx: 1, cy: 4, stamp: "세운술통" },
            { cx: 0, cy: 4, stamp: "세운술통" },
            { cx: 9, cy: 0, stamp: "세운술통" },
            { cx: 9, cy: 1, stamp: "세운술통" },
            { cx: 10, cy: 1, stamp: "세운술통" },
            { cx: 7, cy: 2, stamp: "세운술통" },
            { cx: 6, cy: 2, stamp: "세운술통" },
            { cx: 6, cy: 3, stamp: "세운술통" },
            { cx: 7, cy: 3, stamp: "세운술통" },
            { cx: 4, cy: 2, stamp: "세운술통" },
            { cx: 3, cy: 2, stamp: "세운술통" },
            { cx: 3, cy: 1, stamp: "세운술통" },
            { cx: 4, cy: 1, stamp: "세운술통" }
        ] },
    { id: "o_15", spawn: { cx: 5, cy: 5 }, minSteps: 26, hamiltonian: true, obstacles: [
            { cx: 10, cy: 0, stamp: "작은박스더미" },
            { cx: 0, cy: 0, stamp: "작은박스더미" },
            { cx: 1, cy: 0, stamp: "작은박스더미" },
            { cx: 2, cy: 0, stamp: "술박스" },
            { cx: 9, cy: 0, stamp: "술박스" },
            { cx: 3, cy: 0, stamp: "세운술통" },
            { cx: 4, cy: 0, stamp: "세운술통" },
            { cx: 5, cy: 0, stamp: "세운술통" },
            { cx: 6, cy: 0, stamp: "세운술통" },
            { cx: 7, cy: 0, stamp: "세운술통" },
            { cx: 8, cy: 0, stamp: "포대2" },
            { cx: 10, cy: 1, stamp: "세운술통" },
            { cx: 9, cy: 1, stamp: "세운술통" },
            { cx: 9, cy: 2, stamp: "세운술통" },
            { cx: 10, cy: 2, stamp: "세운술통" },
            { cx: 10, cy: 3, stamp: "세운술통" },
            { cx: 9, cy: 3, stamp: "세운술통" },
            { cx: 9, cy: 4, stamp: "세운술통" },
            { cx: 10, cy: 4, stamp: "세운술통" },
            { cx: 10, cy: 5, stamp: "세운술통" },
            { cx: 9, cy: 5, stamp: "세운술통" },
            { cx: 8, cy: 5, stamp: "세운술통" },
            { cx: 4, cy: 1, stamp: "세운술통" },
            { cx: 5, cy: 1, stamp: "세운술통" },
            { cx: 6, cy: 1, stamp: "세운술통" },
            { cx: 6, cy: 2, stamp: "세운술통" },
            { cx: 5, cy: 2, stamp: "세운술통" },
            { cx: 4, cy: 2, stamp: "세운술통" },
            { cx: 0, cy: 1, stamp: "세운술통" },
            { cx: 1, cy: 1, stamp: "세운술통" },
            { cx: 1, cy: 2, stamp: "세운술통" },
            { cx: 0, cy: 2, stamp: "세운술통" },
            { cx: 0, cy: 3, stamp: "세운술통" },
            { cx: 1, cy: 3, stamp: "세운술통" },
            { cx: 1, cy: 4, stamp: "세운술통" },
            { cx: 0, cy: 4, stamp: "세운술통" },
            { cx: 0, cy: 5, stamp: "세운술통" },
            { cx: 1, cy: 5, stamp: "세운술통" },
            { cx: 2, cy: 5, stamp: "세운술통" }
        ] },
    { id: "o_16", spawn: { cx: 5, cy: 5 }, minSteps: 47, hamiltonian: true, obstacles: [
            { cx: 5, cy: 0, stamp: "술박스" },
            { cx: 5, cy: 3, stamp: "포대1" },
            { cx: 8, cy: 1, stamp: "세운술통" },
            { cx: 9, cy: 1, stamp: "세운술통" },
            { cx: 7, cy: 1, stamp: "세운술통" },
            { cx: 7, cy: 2, stamp: "세운술통" },
            { cx: 7, cy: 3, stamp: "세운술통" },
            { cx: 7, cy: 4, stamp: "세운술통" },
            { cx: 8, cy: 4, stamp: "세운술통" },
            { cx: 9, cy: 4, stamp: "세운술통" },
            { cx: 1, cy: 4, stamp: "세운술통" },
            { cx: 2, cy: 4, stamp: "세운술통" },
            { cx: 3, cy: 4, stamp: "세운술통" },
            { cx: 3, cy: 3, stamp: "세운술통" },
            { cx: 3, cy: 2, stamp: "세운술통" },
            { cx: 3, cy: 1, stamp: "세운술통" },
            { cx: 2, cy: 1, stamp: "세운술통" },
            { cx: 1, cy: 1, stamp: "세운술통" }
        ] },
    { id: "o_17", spawn: { cx: 5, cy: 5 }, minSteps: 46, hamiltonian: false, obstacles: [
            { cx: 8, cy: 1, stamp: "세운술통" },
            { cx: 7, cy: 1, stamp: "세운술통" },
            { cx: 6, cy: 1, stamp: "세운술통" },
            { cx: 5, cy: 1, stamp: "세운술통" },
            { cx: 4, cy: 1, stamp: "세운술통" },
            { cx: 3, cy: 1, stamp: "세운술통" },
            { cx: 2, cy: 1, stamp: "세운술통" },
            { cx: 1, cy: 1, stamp: "세운술통" },
            { cx: 1, cy: 2, stamp: "세운술통" },
            { cx: 1, cy: 3, stamp: "세운술통" },
            { cx: 1, cy: 4, stamp: "세운술통" },
            { cx: 2, cy: 4, stamp: "세운술통" },
            { cx: 3, cy: 4, stamp: "세운술통" },
            { cx: 10, cy: 4, stamp: "세운술통" },
            { cx: 10, cy: 3, stamp: "세운술통" },
            { cx: 8, cy: 3, stamp: "세운술통" },
            { cx: 8, cy: 4, stamp: "세운술통" },
            { cx: 7, cy: 3, stamp: "세운술통" },
            { cx: 10, cy: 0, stamp: "술박스" },
            { cx: 10, cy: 5, stamp: "작은박스더미" }
        ] },
    { id: "o_18", spawn: { cx: 5, cy: 5 }, minSteps: 55, hamiltonian: true, obstacles: [
            { cx: 4, cy: 5, stamp: "작은박스더미" },
            { cx: 0, cy: 5, stamp: "작은박스더미" },
            { cx: 4, cy: 4, stamp: "세운술통" },
            { cx: 4, cy: 1, stamp: "세운술통" },
            { cx: 6, cy: 2, stamp: "세운술통" },
            { cx: 6, cy: 0, stamp: "세운술통" },
            { cx: 2, cy: 2, stamp: "세운술통" },
            { cx: 8, cy: 1, stamp: "술박스" },
            { cx: 10, cy: 2, stamp: "술박스" },
            { cx: 9, cy: 4, stamp: "술박스" }
        ] },
    { id: "o_19", spawn: { cx: 5, cy: 5 }, minSteps: 50, hamiltonian: true, obstacles: [
            { cx: 9, cy: 1, stamp: "술박스" },
            { cx: 3, cy: 1, stamp: "작은박스더미" },
            { cx: 1, cy: 4, stamp: "작은박스더미" },
            { cx: 8, cy: 1, stamp: "세운술통" },
            { cx: 7, cy: 1, stamp: "세운술통" },
            { cx: 6, cy: 1, stamp: "세운술통" },
            { cx: 2, cy: 1, stamp: "세운술통" },
            { cx: 1, cy: 1, stamp: "세운술통" },
            { cx: 2, cy: 4, stamp: "세운술통" },
            { cx: 3, cy: 4, stamp: "세운술통" },
            { cx: 4, cy: 4, stamp: "세운술통" },
            { cx: 9, cy: 4, stamp: "세운술통" },
            { cx: 8, cy: 4, stamp: "세운술통" },
            { cx: 7, cy: 4, stamp: "세운술통" },
            { cx: 6, cy: 3, stamp: "포대2" }
        ] }
];
